name: Preprocessing

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout preprocessing repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: |
          pip install pandas numpy scikit-learn

      - name: Run preprocessing
        run: |
          python preprocessing/automate_Kadek_Andra_Wikanjaya_Putra.py

      - name: Commit preprocessing output to preprocessing repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add -A

          if git diff --cached --quiet; then
            echo "No changes to commit in preprocessing repo"
          else
            git commit -m "Auto: update preprocessing dataset"
            git push
          fi

      - name: Clone workflow-ci repository
        run: |
          git clone https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/USERNAME/workflow-ci.git workflow-ci

      - name: Copy preprocessing output to workflow-ci
        run: |
          cp preprocessing/*.csv workflow-ci/MLProject/

      - name: Commit preprocessing output to workflow-ci repo
        run: |
          cd workflow-ci
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add -A

          if git diff --cached --quiet; then
            echo "No changes to commit in workflow-ci repo"
          else
            git commit -m "Auto: sync preprocessing dataset"
            git push
          fi
